// Game arithmetic
const CHARACTERS_PER_WORD = 5;

// Local storage
const LOCAL_STORAGE_FLOAT_DECIMAL_PLACES = 4;
const LOCAL_STORAGE_COUNT_DECIMAL_PLACES = 0;

// Unit conversions
const MILLISECONDS_PER_SECOND = 1000;
const SECONDS_PER_MINUTE = 60;
const SECONDS_PER_HOUR = 3600;
const MINUTES_PER_HOUR = 60;